# Generated by Django 4.1.4 on 2022-12-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('job', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=60)),
                ('cnpj', models.CharField(max_length=60)),
            ],
        ),
    ]
