version: "3.8"

services:

  app:
    container_name: django
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - "./app:/app"
    command:  >
      sh -c "python3 manage.py migrate &&
             python3 manage.py validate_db_connection &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:15-alpine
    env_file:
      - ./.env

  redis:
    container_name: redis
    image: redis:7-alpine

  celery:
    container_name: celery
    restart: always
    build:
      context: .
    command: celery -A app worker -l info
    volumes:
      - "./app:/app"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - app

  flower:
    container_name: flower
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - FLOWER_PORT=8888
    ports:
      - 8888:8888